<!DOCTYPE html>
<html>
<!-- the head section -->
<head>

    <title>Mi Melee H2H</title>
    <link rel="stylesheet" type="text/css" href="/mi_melee_h2h/styles/normalize.css">
    <link rel="stylesheet" type="text/css" href="/mi_melee_h2h/styles/main.css">
    <script type="text/javascript" src="searchabledropdown/sh/shCore.js"></script>
  	<script type="text/javascript" src="searchabledropdown/sh/shBrushJScript.js"></script>

  	<script type="text/javascript"> SyntaxHighlighter.all() </script>

  	<script type="text/javascript" src="http://ajax.googleapis.com/ajax/libs/jquery/1.8.3/jquery.min.js"></script>
  	<script type="text/javascript" src="searchabledropdown/jquery.searchabledropdown-1.0.8.min.js"></script>


  	<script type="text/javascript">
  		$(document).ready(function() {
  			$("select").searchable(
          {
            maxListSize: 10,                       // if list size are less than maxListSize, show them all
            maxMultiMatch: 10,                      // how many matching entries should be displayed
            exactMatch: false,                      // Exact matching on search
            wildcards: true,                        // Support for wildcard characters (*, ?)
            ignoreCase: true,                       // Ignore case sensitivity
            latency: 200,                           // how many millis to wait until starting search
            warnMultiMatch: 'top {0} matches ...',  // string to append to a list of entries cut short by maxMultiMatch
            warnNoMatch: 'no matches ...',          // string to show in the list when no entries match
            zIndex: 'auto'                          // zIndex for elements generated by this plugin
          }
        );
  		});
  	</script>

</head>

<!-- the body section -->
<body>
<header>
    <h1>Michigan Melee Head to Head</h1>
    <p></p>
    <nav>
    </nav>
</header>
